import Head from "next/head";

import styles from "@/styles/Home.module.css";
import CustomHeader from "@/components/gnb/CustomHeader";
import { useState } from "react";

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(true); // 임시로 로그인 여부 판단해 놓은거입니다.

  const handleLogoutClick = () => {
    if (isLoggedIn) {
      setIsLoggedIn(false);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}></main>
        <CustomHeader
          isLoggedIn={isLoggedIn}
          href="/myprofile"
          pagename="내 프로필"
          handleLogoutClick={handleLogoutClick}
        />
      </div>
    </>
  );
}
